# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload to Testflight"
  lane :beta do
    apple_id = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    scheme = "Fastlane Demo"

    scan(scheme: scheme, only_testing: ["Fastlane DemoTests/Fastlane_DemoTests.swift"])
    cert(username: apple_id)
    sigh(username: apple_id, app_identifier: app_identifier)
    increment_build_number()
    build(scheme: scheme)
    pilot(username: apple_id)
    puts "Everything is fine :)"
  end

  lane :build do |options|
    build_ios_app(scheme: options[:scheme])
  end
end
